### ISSUE TITLE
Samples inputbox doesn't work

### ISSUE THREAD

**Issue by kritollm** [pmros/cyclow#2]
`'dom.focus': () => ({'dom.action': node => node.firstElementChild.focus()})`

Node is undefined.

I'm not into the graflow library so I don't know how the Memorizer is supposed to have any information about the node, but the memory is undefined `(node = _ref.memory; //=> undefined)`

**Comment by pmros** [comment]
It seems something about Snabbdom and `create` hook. If I change line 10 of inputbox example by this one:
```js
  view: text => ({tag: 'div.x', content: [
```
it seems to work OK. 
I have to spend more time debugging this issue. I'll try to fix it soon.

Thank you kritollm.

**Comment by pmros** [comment]
I think it's a Snabbdom issue so I've created this:
https://github.com/snabbdom/snabbdom/issues/268

Until it will be solved, it's better to use `target` option for `run`. So insted of: `run(InputBox)`, use `run(InputBox, {target: 'app'}`. You have to add `<div id="app"></div>` to the html file. 

Well, I'll make these changes in the next cyclow release (very soon). I'll close this issue then.

**Comment by pmros** [comment]
Fixed in cyclow 0.5.3!
I've changed `create` hook by `update`hook, as TylorS suggested (from Snabbdom issue).
I close this issue. Thank you, @kritollm.
