### ISSUE TITLE
A couple of typos in README

### ISSUE THREAD

**Issue by gamtiq** [pmros/cyclow#3]
There are the following typos in `README.md`:
> In *adition*, you can add your own blocks or custom blocks with blocks Block option.
> From counter *exaple*
> It creates a component that takes a Virtual DOM Element as *a* input and it converts

**Comment by pmros** [comment]
Thank you very much @gamtiq. Fixed!
By the way, you can edit README.md directly. If you do it, Github would make a repo clone and a pull request automatically. Finally I'd review the pull request and I'd accept it.
Thank you again @gamtiq.
