### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by thiamsantos** [pmros/cyclow#4]
There is anything that I can do to help the project?

**Comment by pmros** [comment]
Hello @thiamsantos,
I have to add a CONTRIBUTING guide to cyclow I think the priorities are:
* Create a project that uses cyclow. I could add a "project using cyclow" section.
* Find/fix bugs.
* Write more documentation. You could post an article about Cyclow at Medium, for example.

Thank you @thiamsantos.

**Comment by thiamsantos** [comment]
Cool @pmros!!!

I noticed that you use [webpack](https://webpack.js.org/) as bundler, what do you think about use [rollup](http://rollupjs.org/) because rollup create a smaller bundle and is [more recommended](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c) to use with lib development.

Other things that I thought:
- [Gulp](http://gulpjs.com/) is really necessary? Maybe some npm scripts could be enough for the project.
- There are plans to add unit tests? And some test coverage tools?
- What about use some configured styleguide like [xo](https://github.com/sindresorhus/xo) or [standardjs](https://standardjs.com/)? Would be nice to use as well [prettier](https://github.com/prettier/prettier) as code formatter.
- Another thing that could be done is to add [Git Hooks](https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks), in order to prevent the contributors to submit code that break the tests or do not follow the stablished styleguide.

**Comment by thiamsantos** [comment]
The following links are good examples of contributing guidelines. Maybe you could them as inspiration:

- https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- https://github.com/avajs/ava/blob/master/contributing.md
- https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md

**Comment by pmros** [comment]
@thiamsantos 
* I used a [boilerplate](https://github.com/babel/generator-babel-boilerplate) to create Cyclow project. To use a boilerplate is not a good practice but it reduces JS fatigue (for lazy people like me). So probably a custom toolchain config would be better.
* Cyclow needs unit tests but I'd like to add more e2e tests first.
* standarjs is in TODO list. Graflow uses standarjs and I like it.
* Cyclow (and Graflow) uses Travis CI.

Thank you @thiamsantos for your CONTRIBUTING links. Your contributions are welcomed!

**Comment by thiamsantos** [comment]
> Thank you @thiamsantos for your CONTRIBUTING links. Your contributions are welcomed!

:tada::tada::tada::tada: Awesome @pmros!

I just found a guide of [how to write a good CONTRIBUTING from Github team](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines).
